#!/bin/bash
# TODO: Look into a real makefile?

OBJECT_DIR="output"
mkdir -p $OBJECT_DIR

OBJECT_FILES="
  chrome.manifest
  chrome
  icon.png
  install.rdf"

rm $OBJECT_DIR/pinterest.xpi
zip -r $OBJECT_DIR/pinterest.xpi $OBJECT_FILES
